services:
  app:
    container_name: ${PROJECT_NAME}-app
    image: ${PROJECT_NAME}-custom:latest
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - "${WP_PORT}:80"
    volumes:
      - ../${PROJECT_NAME}/wp-content:/var/www/html/wp-content
      - ../${PROJECT_NAME}/root:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  pma:
    container_name: ${PROJECT_NAME}-pma
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 0
      MEMORY_LIMIT: 0
      MAX_EXECUTION_TIME: 0
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}-db
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ../${PROJECT_NAME}/data:/var/lib/mysql
