version: "3.8"

services:
  wordpress:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION}
    image: my-wordpress-custom:latest
    container_name: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: ${DATABASE_HOST}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${PORT_HTTP}:80"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: wordpress-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

volumes:
  wordpress_data:
